# -*- coding: utf-8 -*-
"""HOTEL BOOKING1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14huPTNp3BIrEgXiDZX9RZHpOEwfPnk1c
"""

import pandas as  pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as  sns
import  warnings
warnings.filterwarnings('ignore')

"""reading the dataset"""

df=pd.read_csv("/content/archive (10).zip")

df.head()

df.tail()

df.head(5)

df.shape

df.columns

df.info()

df.describe()

df['reservation_status_date']=pd.to_datetime(df['reservation_status_date'])

df.info()

df.describe(include='object')

for col in df.describe(include='object').columns:
  print(col)
  print(df[col].unique())
  print('-'*50)

df.isnull().sum()

df.drop(['company','agent'],axis=1,inplace=True)
df.dropna(inplace=True)

df.isnull().sum()

df.describe()

df=df[df['adr']<5000]

"""data analysis** **and** ***visulisation***"""

cancelled_perc = df['is_canceled'].value_counts(normalize=True)
print(cancelled_perc)




plt.figure(figsize=(8, 4))
plt.title('Reservation status count')
plt.bar(['Not canceled', 'Canceled'], df['is_canceled'].value_counts(), edgecolor='pink', width=0.5)
plt.show()

plt.figure(figsize=(8,4))
ax1=sns.countplot(x='hotel',hue='is_canceled',data=df,palette='Blues')

plt.xlabel('hotel')
plt.ylabel('number of reservation')
plt.title('Reservation of different hotels',size=20)

plt.show()

resort_hotel=df[df['hotel']=='Resort Hotel']
resort_hotel['is_canceled'].value_counts(normalize=True)

city_hotel=df[df['hotel']=='City Hotel']
city_hotel['is_canceled'].value_counts(normalize=True)

plt.figure(figsize=(20,6))
plt.title('Average Daily Rate in City Hotel and Resort Hotel', fontsize=30)
plt.plot(resort_hotel.index,resort_hotel['adr'],label='resort_hotel' )
plt.plot(city_hotel.index,city_hotel['adr'],label='city_hotel')
plt.legend(fontsize=20)
plt.show()

df['month']=df['reservation_status_date'].dt.month
plt.figure(figsize=(16,8))
sns.countplot(x='month',hue='is_canceled',data=df,palette='Blues')
plt.title('Reservation Satause per Month',fontsize=20)
plt.xlabel=('month')
plt.ylabel('number of reservation')
plt.legend(['canceled','notcanceled'])
plt.show()

plt.figure(figsize=(13, 5))
plt.title('ADR per month', fontsize=20)

canceled_reservations = df[df['is_canceled'] == 1]


monthly_adr_sum = canceled_reservations.groupby('month')['adr'].sum().reset_index()

sns.barplot(x='month', y='adr', data=monthly_adr_sum)

plt.show()

canceled_data=df[df['is_canceled']==1]
top_10_countries= canceled_data['country'].value_counts()[:10]
plt.figure(figsize=(8,8))
plt.title('Top 10 Countries With Reservations Canceled')
plt.pie(top_10_countries,autopct='%.2f',labels=top_10_countries.index)
plt.show()

"""market segment distribution"""

df['market_segment'].value_counts()

df['market_segment'].value_counts(normalize=True)